
**`kubernetes/helm/speech4kids/values.yaml`**
```yaml```
replicaCount: 3
image:
  repository: speech4kids/gateway
  tag: latest
  pullPolicy: Always
service:
  type: LoadBalancer
  port: 80
resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "1"
