### 1. Prometheus
#### prometheus.yml
```yaml
# Prometheus Configuration
# Scrapes metrics from microservices and exposes them for Grafana visualization

global:
  scrape_interval: 15s  # How often to scrape targets by default
  evaluation_interval: 15s  # How often to evaluate rules by default

scrape_configs:
  - job_name: "gateway"
    static_configs:
      - targets: ["gateway:8000"]

  - job_name: "asr_service"
    static_configs:
      - targets: ["asr_service:8001"]

  - job_name: "tts_service"
    static_configs:
      - targets: ["tts_service:8002"]

  - job_name: "nlp_service"
    static_configs:
      - targets: ["nlp_service:8003"]
```